global:
  acrLoginServer: aegisprodacr.azurecr.io
  imageTag: latest

imageTags:
  api-gateway: "latest"
  health-records-service: "latest"
  medication-service: "latest"
  ai-service: "latest"
  notification-worker: "latest"
  imaging-service: "latest"
  diagnostic-agent-service: "latest"
  coordinator-agent: "latest"
  image-analysis-agent: "latest"
  patient-history-agent: "latest"
  client: "latest"

namespace:
  name: aegis-prod

workloadIdentity:
  clientId: ""  # set after prod terraform apply

keyVault:
  name: aegis-kv-prod
  tenantId: "3076b773-f5d9-413e-9564-7deaa3d0d7b7"
