replicaCount: 1

image:
  acrLoginServer: aegistestacr.azurecr.io
  tag: "sha-be9b524"

resources:
  requests:
    cpu: 30m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 128Mi

hpa:
  enabled: false
