replicaCount: 1

image:
  acrLoginServer: aegistestacr.azurecr.io
  tag: "sha-d67694b"

resources:
  requests:
    cpu: 50m
    memory: 96Mi
  limits:
    cpu: 250m
    memory: 256Mi

hpa:
  enabled: false

env:
  NODE_ENV: development
