{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: diagnostic-agent-service-netpol
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "diagnostic-agent-service.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "diagnostic-agent-service.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: coordinator-agent
      ports:
        - protocol: TCP
          port: 5005
  egress:
    - {}
{{- end }}
