{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aegis-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
spec:
  ingressClassName: azure-application-gateway
  rules:
    - http:
        paths:
          - path: /api/history
            pathType: Prefix
            backend:
              service:
                name: health-records-service
                port:
                  number: 5001
          - path: /api/appointments
            pathType: Prefix
            backend:
              service:
                name: health-records-service
                port:
                  number: 5001
          - path: /api/medications
            pathType: Prefix
            backend:
              service:
                name: medication-service
                port:
                  number: 5002
          - path: /api/caregiver
            pathType: Prefix
            backend:
              service:
                name: medication-service
                port:
                  number: 5002
          - path: /api/status
            pathType: Prefix
            backend:
              service:
                name: medication-service
                port:
                  number: 5002
          - path: /api/ai
            pathType: Prefix
            backend:
              service:
                name: ai-service
                port:
                  number: 5003
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-gateway-service
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: 80
{{- end }}
