apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aegis-kv-secret-provider
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  secretObjects:
    - secretName: aegis-kv-secrets
      type: Opaque
      data:
        {{- range .Values.keyVault.secrets }}
        - objectName: {{ .kvName }}
          key: {{ .key }}
        {{- end }}
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.workloadIdentity.clientId | quote }}
    keyvaultName: {{ .Values.keyVault.name | quote }}
    cloudName: ""
    tenantId: {{ .Values.keyVault.tenantId | quote }}
    objects: |
      array:
        {{- range .Values.keyVault.secrets }}
        - |
          objectName: {{ .kvName }}
          objectType: secret
        {{- end }}
