apiVersion: v1
kind: ServiceAccount
metadata:
  name: aegis-workload-identity
  namespace: {{ .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.clientId | quote }}
  labels:
    azure.workload.identity/use: "true"
