replicaCount: 1
image:
  acrLoginServer: aegistestacr.azurecr.io
  tag: "v0.2.1"
resources:
  requests:
    cpu: 30m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 256Mi
hpa:
  enabled: false
env:
  NODE_ENV: development
