replicaCount: 2

image:
  acrLoginServer: aegistestacr.azurecr.io

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 70
  memoryUtilization: 80

resources:
  requests:
    cpu: 100m
    memory: 192Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  NODE_ENV: production

