apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: client-prod
  namespace: argocd
  labels:
    env: prod
    app: client
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/health-aegis/k8s-manifests.git
    targetRevision: HEAD
    path: charts/client
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: aegis-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
