apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coordinator-agent-prod
  namespace: argocd
  labels:
    env: prod
    app: coordinator-agent
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/health-aegis/health-aegis.git
    targetRevision: HEAD
    path: helm/charts/coordinator-agent
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: aegis-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
